# Generated by Django 5.2.1 on 2025-06-14 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Artigo')),
                ('descricao', models.TextField(verbose_name='Descrição/Justificativa')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovada', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_artigo_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_artigo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Artigo',
                'verbose_name_plural': 'Solicitações de Artigo',
            },
        ),
    ]
